# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(default='', verbose_name='\u673a\u6784\u540d\u79f0'),
        ),
    ]
