# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(default='', verbose_name='\u673a\u6784\u63cf\u8ff0'),
        ),
    ]
